name: Run News_Spread_Engine

on:
  workflow_dispatch:

jobs:
  run-engine:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run engine
      run: |
        python main.py

    - name: Save logs
      run: |
        echo "Logs from run:" >> logs.txt
        cat logs.txt
